/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package waste.application;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        setBackground(new Color(0,0,0));
        viewpane.setEnabled(false);
        viewpane.setVisible(false);
         set1.setEnabled(false);
     set1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        set2 = new javax.swing.JLabel();
        set1 = new javax.swing.JLabel();
        profilepane = new javax.swing.JPanel();
        viewprofile = new javax.swing.JLabel();
        viewpane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        viewsetting = new javax.swing.JLabel();
        faqspane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        schedulepane = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        historypane = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pickuppane = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        settingspane = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        helppane = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        viewmenu = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        set2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                set2MouseClicked(evt);
            }
        });
        getContentPane().add(set2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 496, 80, 50));

        set1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                set1MouseClicked(evt);
            }
        });
        getContentPane().add(set1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 80, 50));

        profilepane.setOpaque(false);
        profilepane.setLayout(null);

        viewprofile.setForeground(new java.awt.Color(255, 255, 255));
        viewprofile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewprofileMouseClicked(evt);
            }
        });
        profilepane.add(viewprofile);
        viewprofile.setBounds(0, 0, 80, 50);

        getContentPane().add(profilepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 80, 50));

        viewpane.setLayout(null);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        viewpane.add(jLabel2);
        jLabel2.setBounds(0, 0, 160, 40);

        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        viewpane.add(jLabel11);
        jLabel11.setBounds(20, 100, 80, 20);

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setOpaque(true);
        viewpane.add(jLabel10);
        jLabel10.setBounds(0, 50, 160, 30);

        viewsetting.setBackground(new java.awt.Color(255, 255, 255));
        viewsetting.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\images\\settings.JPG")); // NOI18N
        viewpane.add(viewsetting);
        viewsetting.setBounds(0, 0, 157, 130);

        getContentPane().add(viewpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 160, 130));

        faqspane.setOpaque(false);
        faqspane.setLayout(null);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        faqspane.add(jLabel3);
        jLabel3.setBounds(0, 0, 170, 220);

        getContentPane().add(faqspane, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 170, 220));

        schedulepane.setOpaque(false);
        schedulepane.setLayout(null);

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        schedulepane.add(jLabel4);
        jLabel4.setBounds(0, 0, 160, 200);

        getContentPane().add(schedulepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 160, 200));

        historypane.setOpaque(false);
        historypane.setLayout(null);

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        historypane.add(jLabel5);
        jLabel5.setBounds(0, 0, 160, 200);

        getContentPane().add(historypane, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 160, 200));

        pickuppane.setOpaque(false);
        pickuppane.setLayout(null);

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        pickuppane.add(jLabel6);
        jLabel6.setBounds(0, 0, 170, 200);

        getContentPane().add(pickuppane, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 170, 200));

        settingspane.setOpaque(false);
        settingspane.setLayout(null);

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        settingspane.add(jLabel7);
        jLabel7.setBounds(0, 0, 160, 220);

        getContentPane().add(settingspane, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, 160, 220));

        helppane.setOpaque(false);
        helppane.setLayout(null);

        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        helppane.add(jLabel8);
        jLabel8.setBounds(0, 0, 170, 220);

        getContentPane().add(helppane, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 180, 220));
        getContentPane().add(viewmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 600, 460));

        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });
        getContentPane().add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 100, 20));

        jLabel9.setBackground(new java.awt.Color(0, 102, 0));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\waste application\\src\\waste\\application\\menua.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     for(double i = 0.0; i<=1.0;i=i+0.1)
     {
      String val =  i+"";
      float f = Float.valueOf(val);
      this.setOpacity(f);
      try {
          Thread.sleep(50);
          
      }
      catch(Exception e)
      {
          
      }
     }
    }//GEN-LAST:event_formWindowOpened

    private void set2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_set2MouseClicked
        viewpane.setEnabled(true);
        viewpane.setVisible(true);
         set1.setEnabled(true);
     set1.setVisible(true);
      set2.setEnabled(false);
     set2.setVisible(false);
    }//GEN-LAST:event_set2MouseClicked

    private void set1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_set1MouseClicked
    
        viewpane.setEnabled(false);
        viewpane.setVisible(false);
          set1.setEnabled(false);
     set1.setVisible(false);
      set2.setEnabled(true);
     set2.setVisible(true);
    }//GEN-LAST:event_set1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
             new log2().setVisible(true);
             this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
new FAQS().setVisible(true);
this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void viewprofileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewprofileMouseClicked
new profile().setVisible(true);
this.dispose();
    }//GEN-LAST:event_viewprofileMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       new pickupschedule().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        new collectionhistory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
     new collectionpickup().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
new settings().setVisible(true);
this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
     JOptionPane.showMessageDialog(this, "contact : \n"
                + "Email : irungubrian09@gmail.com \n"
                + "Telephone Number : 0717185618 \n"
                + "OR : 0769582459");
    }//GEN-LAST:event_jLabel8MouseClicked

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        this.dispose();
        new collectionpickup().setVisible(true);
    }//GEN-LAST:event_dashboardMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
          this.dispose();
        new log2().setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboard;
    private javax.swing.JPanel faqspane;
    private javax.swing.JPanel helppane;
    private javax.swing.JPanel historypane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pickuppane;
    private javax.swing.JPanel profilepane;
    private javax.swing.JPanel schedulepane;
    private javax.swing.JLabel set1;
    private javax.swing.JLabel set2;
    private javax.swing.JPanel settingspane;
    private javax.swing.JLabel viewmenu;
    private javax.swing.JPanel viewpane;
    private javax.swing.JLabel viewprofile;
    private javax.swing.JLabel viewsetting;
    // End of variables declaration//GEN-END:variables

    static class name2 {

        static void setText(String string) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public name2() {
        }
    }

    private static class help {

        public help() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
}
